# Generated by Django 6.0.1 on 2026-02-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_alter_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, default='static/imagens/default-perfil.jpg', null=True, upload_to='foto_perfil'),
        ),
    ]
