# Generated by Django 6.0.1 on 2026-01-21 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos')])),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('celular', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Celular deve conter 10 ou 11 dígitos')])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'CEP deve conter 8 dígitos')])),
                ('numero', models.CharField(max_length=10)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('especialidade', models.CharField(choices=[('CLINICO_GERAL', 'Clínico Geral'), ('PEDIATRIA', 'Pediatria')], max_length=20)),
                ('status', models.CharField(choices=[('ATIVO', 'Em Atividade'), ('FERIAS', 'Férias'), ('DESLIGADO', 'Desligado')], default='ATIVO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['nome_completo'],
            },
        ),
    ]
