# Generated by Django 6.0.1 on 2026-01-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil'),
        ),
    ]
