# Generated by Django 6.0.1 on 2026-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_alter_medico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto',
            field=models.ImageField(blank=True, default='static/imagens/default-perfil.jpg', null=True, upload_to='static/imagens'),
        ),
    ]
