# Generated by Django 6.0.1 on 2026-01-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField(blank=True, null=True)),
                ('tipo_consulta', models.CharField(choices=[('CLINICO_GERAL', 'Clínico Geral'), ('PEDIATRIA', 'Pediatria')], max_length=20)),
                ('sintomas', models.TextField(blank=True, help_text='Sintomas relatados pelo paciente')),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA_PACIENTE', 'Cancelada pelo Paciente'), ('CANCELADA_MEDICO', 'Cancelada pelo Médico')], default='AGENDADA', max_length=20)),
                ('diagnostico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações do médico')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Avaliação do paciente (1 a 5 estrelas)', null=True)),
                ('comentario_avaliacao', models.TextField(blank=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='medico.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-data_consulta', '-horario_inicio'],
                'unique_together': {('medico', 'data_consulta', 'horario_inicio')},
            },
        ),
    ]
